timer:
  mode:
    class-mode: simple
    method-mode: param
    time-mode: simple
    unit: milliseconds
  format:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  tomcat:
    max-threads: 10000
    accept-count: 1000
    min-spare-threads: 30
